name:              Lani Huang
markdown: kramdown
highlighter: rouge
permalink:         /blog/:categories/:year/:month/:day/:title.html
gems:              ['jekyll-sitemap', 'jekyll-paginate']

# kramdown:
#   input:           GFM
#   syntax_highlighter: rouge
#   syntax_highlighter_opts:
#     css_class:     'highlight'

paginate:          5
paginate_path:     'blog/page:num/'