name:              Lani Huang
permalink:         /blog/:categories/:year/:month/:day/:title.html
gems:              ['jekyll-sitemap', 'jekyll-paginate']

markdown: kramdown
kramdown:
  input:           GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class:     'highlight'

paginate:          5
paginate_path:     'blog/page:num/'
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Projects
    url: /projects/
  - title: Contact
    url: /contact/
excerpt_separator: <!--more-->
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - .ruby-gemset
  - .ruby-version
  - .rvmrc
  - node_modules
  - gulpfile.js