name:              Lani Huang
permalink:         /blog/:categories/:year/:month/:day/:title.html
gems:              ['jekyll-sitemap', 'jekyll-paginate']

markdown: kramdown
kramdown:
  input:           GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class:     'highlight'

paginate:          5
paginate_path:     'blog/page:num/'
excerpt_separator: <!--more-->
exclude:           ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']