courses:
  - {
      name: "Modern React with Redux",
      link: "//www.udemy.com/certificate/UC-OK083PRL/",
      date: 01/28/2017,
    }
  - {
      name: Powering Up With React,
      link: "//www.codeschool.com/users/874984/badges/624",
      date: 11/20/2016,
    }
  - {
      name: "ES2015: The Shape of JavaScript to Come",
      link: "//www.codeschool.com/users/874984/badges/575",
      date: 11/20/2016,
    }
  - {
      name: JavaScript Road Trip Part 3,
      link: "//www.codeschool.com/users/874984/badges/321",
      date: 11/19/2016,
    }
  - {
      name: "Practical PHP: Master the Basics and Code Dynamic Websites",
      link: "//www.udemy.com/certificate/UC-4B71AONA/",
      date: 10/08/2016,
    }
  - {
      name: WordPress Theme Development with Bootstrap,
      link: "//www.udemy.com/certificate/UC-L9WGVDZB/",
      date: 10/07/2016,
    }
  - {
      name: CSS Cross-Country,
      link: "//www.codeschool.com/users/874984/badges/40",
      date: 03/2016,
    }
  - {
      name: Try jQuery,
      link: "//www.codeschool.com/users/874984/badges/191",
      date: 03/2016,
    }
  - {
      name: JavaScript Road Trip Part 1,
      link: "//www.codeschool.com/users/874984/badges/296",
      date: 03/2016,
    }
  - {
      name: Fundamentals of Design,
      link: "//www.codeschool.com/users/874984/badges/277",
      date: 03/2016,
    }
  - {
      name: Try Ruby,
      link: "//www.codeschool.com/users/874984/badges/24",
      date: 03/2016,
    }
  - {
      name: Rails for Zombies Redux,
      link: "//www.codeschool.com/users/874984/badges/133",
      date: 03/2016,
    }
  - {
      name: Try Git,
      link: "//www.codeschool.com/users/874984/badges/121",
      date: 02/2016,
    }
  - {
      name: The Complete Web Developer Course,
      link: "//www.udemy.com/certificate/UC-2G9TC9H0/",
      date: 02/25/2016,
    }

social:
  - { name: Email, link: "mailto:laniywh@gmail.com" }
  - { name: GitHub, link: "https://github.com/laniywh" }
  - { name: Twitter, link: "https://twitter.com/laniywh" }
  - { name: CodePen, link: "http://codepen.io/laniywh/" }

projects:
  - {
      name: lanihuang.com,
      folder: lani-huang,
      thumb-extension: .jpg,
      width: 3,
      tags: [htmlcss, javascript, jquery],
    }
  - {
      name: Roguelike Game,
      folder: roguelike-game,
      thumb-extension: .jpg,
      width: 2,
      tags: [javascript, react, fcc],
    }
  - {
      name: Voting App,
      folder: voting-app,
      thumb-extension: .svg,
      width: 3,
      tags: [htmlcss, javascript],
    }
  - {
      name: Minesweeper,
      folder: minesweeper,
      thumb-extension: .jpg,
      width: 3,
      tags: [htmlcss, javascript, top],
    }
  - {
      name: Game of Life,
      folder: game-of-life,
      thumb-extension: .svg,
      width: 2,
      tags: [htmlcss, javascript, fcc, react],
    }
  - {
      name: Snake Game,
      folder: snake,
      thumb-extension: .jpg,
      width: 3,
      tags: [javascript, jquery, top],
    }
  - {
      name: Portfolio in WordPress,
      folder: lhp,
      thumb-extension: .jpg,
      width: 4,
      tags: [htmlcss, other],
    }
  - {
      name: Bootstrap to WordPress,
      folder: b2w,
      thumb-extension: .jpg,
      width: 4,
      tags: [htmlcss, other],
    }
  - {
      name: Search Movies,
      folder: search-movies,
      thumb-extension: .jpg,
      width: 3,
      tags: [javascript, jquery, top],
    }
  - {
      name: Golden Age Village,
      folder: golden-age-village,
      thumb-extension: .jpg,
      width: 3,
      tags: [htmlcss, other],
    }
  - {
      name: Calculator,
      folder: calculator,
      thumb-extension: .jpg,
      width: 2,
      tags: [javascript, jquery, top],
    }
  - {
      name: Tic Tac Toe,
      folder: tic-tac-toe,
      thumb-extension: .jpg,
      width: 4,
      tags: [javascript],
    }
  - {
      name: Mastermind,
      folder: mastermind,
      thumb-extension: .jpg,
      width: 4,
      tags: [top, other],
    }
  - {
      name: Franklin's Fine Dining,
      folder: franklins-fine-dining,
      thumb-extension: .jpg,
      width: 3,
      tags: [other],
    }
  - {
      name: Sketchpad,
      folder: sketchpad,
      thumb-extension: .jpg,
      width: 2,
      tags: [javascript, jquery, top],
    }
  - {
      name: Image Slider,
      folder: image-slider,
      thumb-extension: .svg,
      width: 3,
      tags: [javascript, top],
    }
  - {
      name: Form Validation,
      folder: form-validation,
      thumb-extension: .svg,
      width: 2,
      tags: [javascript, jquery, top],
    }
  - {
      name: The Next Web Clone,
      folder: tnw-clone,
      thumb-extension: .jpg,
      width: 4,
      tags: [htmlcss, top],
    }
  - {
      name: Hangman,
      folder: hangman,
      thumb-extension: .gif,
      width: 3,
      tags: [top, other],
    }

project-tags:
  - { name: All, class: all }
  - { name: React, class: react }
  - { name: freeCodeCamp, class: fcc }
  - { name: The Odin Project, class: top }
  - { name: JavaScript, class: javascript }
  - { name: jQuery, class: jquery }
  - { name: HTML/CSS, class: htmlcss }
  - { name: Other, class: other }
